### ISSUE TITLE
Certificate warnings for https://beam-wisdoms.clau.se 

### ISSUE THREAD

**Issue by lkarthee** [kvakvs/beam-wisdoms#16]
<img width="676" alt="image" src="https://github.com/kvakvs/beam-wisdoms/assets/2712395/576aa3d9-41d9-4cdd-b03e-6889485816fc">

<img width="654" alt="image" src="https://github.com/kvakvs/beam-wisdoms/assets/2712395/eb811208-c6d0-4f03-95e8-fceab11f752c">

**Comment by lkarthee** [comment]
Thanks for the wonderful book.

**Comment by kvakvs** [comment]
To be fair you aren't entering no financial or personal information there.
But that's what Github does when free hosting custom domains. A solution would be to pay for a shared hosting with auto-certificate.

**Comment by lkarthee** [comment]
I agree that there is no harm. My concern is that SSL is misconfigured and modern browsers show a scary popup and ask user to create exception. 

If I remember correctly GitHub generates SSL certificates for GitHub pages using Let's Encrypt. Can you check docs once ?

**Comment by lkarthee** [comment]
https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

On this page there is a virtual assistant which can help you ?

**Comment by kvakvs** [comment]
Issue has been addressed now, at a monthly cost.
